export const mockPages = [
  {
    id: "7c1561d5-c7fe-426f-95c4-e61fbdb4b211",
    name: "Página Inicial",
    slug: "pagina-inicial",
    content: {
      ROOT: {
        type: { resolvedName: "Element" },
        nodes: ["E8MXpTYEZh", "_2pWHI0cC5"],
        props: {
          id: "ROOT",
          style: {
            height: "auto",
          },
          className: "min-h-[500px] w-full bg-white shadow-sm p-4",
          pageMetadata: {
            pageId: "7c1561d5-c7fe-426f-95c4-e61fbdb4b211",
            parentId: null,
          },
        },
        custom: {
          displayName: "Página",
        },
        hidden: false,
        isCanvas: true,
        displayName: "div",
        linkedNodes: {},
      },
      E8MXpTYEZh: {
        type: {
          resolvedName: "Paragraph",
        },
        nodes: [],
        props: {
          text: "Clique para editar este texto. Você pode adicionar qualquer conteúdo aqui.",
          color: "#111928",
          hidden: false,
          fontSize: 16,
          alignment: "left",
          marginTop: 0,
          lineHeight: 1.5,
          marginBottom: 16,
        },
        custom: {},
        hidden: false,
        parent: "ROOT",
        isCanvas: false,
        displayName: "Parágrafo",
        linkedNodes: {},
      },
      _2pWHI0cC5: {
        type: {
          resolvedName: "Calendar",
        },
        nodes: [],
        props: {
          events: [],
          locale: "pt-BR",
          animation: "fade",
          textColor: "#1f2937",
          dateFormat: "dd/MM/yyyy",
          accentColor: "#2563eb",
          compactMode: false,
          defaultView: "month",
          startWeekOn: "sunday",
          primaryColor: "#3b82f6",
          showEventTime: true,
          firstDayOfWeek: 0,
          secondaryColor: "#93c5fd",
          eventTimeFormat: "24h",
          showWeekNumbers: false,
          showAllDayEvents: true,
          allowEventEditing: true,
          animationDuration: 0.3,
          eventCornerRadius: "rounded-md",
          showEventLocation: true,
          allowEventCreation: true,
          allowEventDeletion: true,
          showEventAttendees: false,
          cellBackgroundColor: "#ffffff",
          todayHighlightColor: "#dbeafe",
          headerBackgroundColor: "#ffffff",
        },
        custom: {},
        hidden: false,
        parent: "ROOT",
        isCanvas: false,
        displayName: "Calendário",
        linkedNodes: {},
      },
    },
    workspaceId: "4a1b7d73-7e51-47f5-9572-78d973f95c08",
    createdAt: "2025-03-26T21:12:51.619Z",
    updatedAt: "2025-03-26T23:11:17.276Z",
    parentId: null,
  },
  {
    id: "9dc7f25b-7c0c-4be7-9839-1e70eead60d5",
    name: "TESTE",
    slug: "teste",
    content: {
      ROOT: {
        type: {
          resolvedName: "Element",
        },
        nodes: [],
        props: {
          style: {
            height: "auto",
          },
          className: "min-h-[500px] w-full bg-white shadow-sm p-4",
          pageMetadata: {
            pageId: "04c87e30-9f27-4872-bb17-c7bbbefb1917",
            parentId: null,
          },
        },
        custom: {
          displayName: "Página",
        },
        hidden: false,
        isCanvas: true,
        displayName: "Página",
        linkedNodes: {},
      },
    },
    workspaceId: "4a1b7d73-7e51-47f5-9572-78d973f95c08",
    createdAt: "2025-03-27T12:05:18.963Z",
    updatedAt: "2025-03-27T12:05:18.963Z",
    parentId: null,
  },
];
